apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
  name: rhel9-dr-vm
  generation: 2
  namespace: default
  labels:
    app: rhel9-dr-vm
    kubevirt.io/dynamic-credentials-support: 'true'
    vm.kubevirt.io/template: rhel9-server-small
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.34.0
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        creationTimestamp: null
        name: rhel9-dr-vm
      spec:
        sourceRef:
          kind: DataSource
          name: rhel9
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: rhel9
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: rhel9-dr-vm
        kubevirt.io/size: small
        network.kubevirt.io/headlessService: headless
    spec:
      accessCredentials:
        - sshPublicKey:
            propagationMethod:
              noCloud: {}
            source:
              secret:
                secretName: idrsa-kubevirt
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 2
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - macAddress: '02:d4:47:00:00:01'
              masquerade: {}
              model: virtio
              name: default
            - bridge: {}
              macAddress: '02:d4:48:00:00:02'
              model: virtio
              name: eth1
              state: up
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
          serial: 1512bf0a-a03a-4c7d-88ec-563540e79f96
        machine:
          type: pc-q35-rhel9.6.0
        memory:
          guest: 4Gi
        resources: {}
      networks:
        - name: default
          pod: {}
        - multus:
            networkName: machine-network
          name: eth1
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: rhel9-dr-vm
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: cloud-user
              password: fiki-xrk5-xsbg
              chpasswd: { expire: False }
          name: cloudinitdisk
